### ISSUE TITLE
What about JsonML?

### ISSUE THREAD

**Issue by manvalls** [mjkaufer/JSML#1]
https://en.wikipedia.org/wiki/JsonML
http://www.jsonml.org/

**Comment by mjkaufer** [comment]
That's pretty neat. It's a lot more concise than what I have now. While it doesn't look tailored for html, it looks as if it could definitely be used for it.

**Comment by mckamey** [comment]
JsonML was originally designed to hold HTML and was generalize to work for any XML. I.e., HTML is what it is primarily used for.
